### ISSUE TITLE
Docker daemon not starting when instance boots up

### ISSUE THREAD

**Issue by jeremyjordan** [resero-labs/docker-utils#15]
When I restart an instance (initially created by `create-dock` and later shut down using AWS console), I get the following error:

```
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial tcp 10.93.134.26:2377: connect: connection refused 
```

I then must manually ssh into the instance and start the daemon in order to use remote Docker. Can we start the daemon automatically when an instance is turned back on?

**Comment by rappdw** [comment]
We have seen this problem in the past. In that manifestation, it was do to the AMI auto-updating. Will look for a more robust fix.

**Comment by rappdw** [comment]
@jeremyjordan I'm trying to reproduce this and am unable to do so. When you restart an EC2 instance from the console, it will often transition into `Instance State: running`. This is often premature and you need to wait for the `Status Checks` to transition from `initializing` to `2/2 checks passed`.

Here's what I did to reproduce.

1) create-dock -m test
2) source dock test
3) docker ps (to verify that docker was running)
4) EC2 console, change instances state for `test` to `stopped`
5) EC2 console, change instance state from `stopped` to `start`
6) Wait for `Status Checks` to transition to `2/2 checks passed`
7) docker ps (to verify that docker is running)

If you are able to reproduce this after waiting for `Status Checks` == `2/2 checks passed`, please provide steps to reproduce as a comment to this issue.

**Comment by rappdw** [comment]
Hmm. I'm seeing this intermittently, even with the wait for status checks. I'll continue to dig in.
