### ISSUE TITLE
No way to pass environment varaibles in run-image

### ISSUE THREAD

**Issue by devonkinghorn** [resero-labs/docker-utils#16]
run-image has no way of passing environment variables to containers.

**Comment by rappdw** [comment]
@devonkinghorn I'm considering the following:

cli: -e var=value
cfg:
```
[<image_name>]
env=<env_section_name>
...
[<env_section_name>]
var1=value1
var2=value2
```
The result would be the same as if you specified
```
ENV var
```
in the dockerfile
