### ISSUE TITLE
Support for --build-arg in build-image

### ISSUE THREAD

**Issue by devonkinghorn** [resero-labs/docker-utils#48]
It would be nice to be able to pass in aws environment variables generated by aws-vault to build-image without the credentials being stored in the image.

https://docs.docker.com/engine/reference/commandline/build/

**Comment by devonkinghorn** [comment]
Or it would be nice to be able to pass in arbitrary flags.
i.e.
```
[image]
--build-arg=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
--build-arg=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
--anotherarg=value
```

**Comment by rappdw** [comment]
@devonkinghorn aren't the credentials generated by aws-vault ephemeral? If so, we don't want them to be build into the image...

**Comment by rappdw** [comment]
In any case docker-utils now supports "build-args" (for build-image) and "args" (for run-image) section under the image 

so:
```
[image]
build_args=--build-arg=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
args=--cap-add SYS_PTRACE 
```
