### ISSUE TITLE
Add ability to show all registered dock monikers + IP address

### ISSUE THREAD

**Issue by zabzug-pfpt** [resero-labs/docker-utils#62]
It would be really nice to be call something like "list-docks" and have it return a small table with a list of all the docks you've registered and some details about them: monikers, IP addresses, instance types, etc.

Currently, the closest solution is to enter your `~/.docker` directory and look at the `connection_config.txt` file for each IP address-defined subdirectory, which is quite onerous.

**Comment by rappdw** [comment]
Have you tried `ls-dock`?

**Comment by zabzug-pfpt** [comment]
Ah, no, I didn’t know it existed! That’s perfect!
